### PR TITLE
Upgrade msal to 4.44

### PR DESCRIPTION
**Pull request by goagain**
# Summary
MSAL 4.44 brings a very exciting change - a C++ wrapped interface to using the Windows Broker natively in MSAL without the extra Microsoft.Identity.Client.Desktop dependency.

That library bloats AzureAuth by nearly 50 MB. Why is that bad? We install AzureAuth, a lot. https://somsubhra.github.io/github-release-stats/?username=AzureAd&repository=microsoft-authentication-cli&page=1&per_page=5 - version 0.3.0 has been downloaded over 100K times already. Making the application small means faster install times which means faster enlistment setup and faster first time usage from within apps.

# Goals:
Upgrade to MSAL 4.44
Remove Microsoft.Identity.Client.Desktop
Ensure all current functionality still works, that we can still use this new version and build and run on Intel and Arm Macs.
# Non-Goals:
Any new functionality
Updating the target framework (We should be able to update to dotnet 6 as well - let's do that as a separate task).

# Update
Upgrade `Microsoft.Identity.Client` from 4.43.1 to 4.44.0
Upgrade `Microsoft.Identity.Client.Extensions.Msal` from 2.19.6 to 2.21.0
Remove `Microsoft.Identity.Client.Desktop` on .NET 4.7.2

# Outcome
Releases don't show a significant size difference.
AzureAuth-win64-msal4.43: 73,105 KB
AzureAuth-win64-msal4.44: 72,988 KB

Executed publish command:
```ps1
dotnet publish .\src\AzureAuth\AzureAuth.csproj --arch=x64 --os=win --self-contained --output=msal4.43 --interactive
```

### CODE REVIEW

**Comment by goagain** [comment]
Need help to test on Mac OS.

**Comment by goagain** [comment]
Updated from @reillysiemens 
" I've built and tested your MSAL 4.44 changes on Mac and they seem to work."

**Review by reillysiemens — APPROVED** [review]
@goagain: From my ARM Mac this looks good. I ran `dotnet build` and `dotnet test` with no errors. I also did a `dotnet publish` to build a release version and manually tested some auth scenarios. 🚢

**Comment by kyle-rader** [comment]
I have also tested on my Arm Mac and Intel Mac - both pass web and device codes cleared and cached.

**Comment by kyle-rader** [comment]
@goagain Can you update the PR description with why this update is special, and also the before and after total size of the Windows published distro?

**Comment by reillysiemens** [comment]
If there isn't a significant reduction in size is there another benefit to us upgrading this dependency? Does anything in [this changelog](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/compare/4.43.1...4.44.0#diff-b40cd67182487ef24807d9c9268329d35fbd96aa2b0a9cae69e2e0d746b1c666) stand out to you, @kyle-rader or @goagain?

**Comment by goagain** [comment]
> If there isn't a significant reduction in size is there another benefit to us upgrading this dependency? Does anything in [this changelog](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/compare/4.43.1...4.44.0#diff-b40cd67182487ef24807d9c9268329d35fbd96aa2b0a9cae69e2e0d746b1c666) stand out to you, @kyle-rader or @goagain?

I looked at the updates and it doesn't seem like there are major improvements we desperately need. But it does have some incremental improvements, and I think we should be able to benefit from the upgrade. This version was released in April with no major bugs heard.

**Comment by reillysiemens** [comment]
That sounds reasonable, @goagain. I'm happy to see this merge, but before we do I'd kinda like to understand why, with this description,

> MSAL 4.44 brings a very exciting change - a C++ wrapped interface to using the Windows Broker natively in MSAL without the extra Microsoft.Identity.Client.Desktop dependency.

we don't see the supposed size decrease. @kyle-rader, is there anyone from the MSAL team we should ask about this? Do they expect we would have seen a size decrease?

**Review by reillysiemens — APPROVED** [review]

**Comment by reillysiemens** [comment]
Any thoughts on the size decrease question here, @bgavrilMS? Is this still a change we want to push through, @kyle-rader &amp; @goagain? 4.45.0 is available as well and I don't see either as especially risky.

**Comment by reillysiemens** [comment]
Closing in favor of #133 for now.

**Pull request closed without merging**
