### PR TITLE
Revert "Stop azureauth before install"

### PR DESCRIPTION
**Pull request by reillysiemens**
Reverts AzureAD/microsoft-authentication-cli#93

### CODE REVIEW

**Review by kyle-rader — APPROVED** [review]

**Comment by reillysiemens** [comment]
For some unknown reason this fails the installer.

**Review by goagain — APPROVED** [review]
What happened here?

**Comment by kyle-rader** [comment]
We get
image

```shell
D:\og1\src>init
Installing AzureAuth v0.3.0
taskkill : ERROR: The process "azureauth.exe" not found.
At C:\Users\kyrader\AppData\Local\Temp\install.ps1:38 char:1
+ taskkill /f /im azureauth.exe 2>&1 | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: The proc...exe" not found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by reillysiemens** [comment]
@goagain: Your guess is as good as mine right now. We'd like to revert ASAP and determine the root cause afterwards.

**Pull request merged**
